services:
  spark-master:
    image: spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    ports: 
      - "8080:8080"
    networks:
      - spark-network

  spark-worker:
    image: spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    networks:
      - spark-network
      
networks:
  spark-network:
    driver: bridge