services:
  spark-master:
    image: spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    volumes:
      - ./data/raw:/data/raw
      - ./src/main/python:/src/main/python
      - ./src/main/scala:/src/main/scala
    entrypoint: >
      /bin/bash -c "
      apt-get update &&
      apt-get install -y apt-transport-https curl gnupg &&
      echo 'deb https://repo.scala-sbt.org/scalasbt/debian all main' > /etc/apt/sources.list.d/sbt.list &&
      curl -sL https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x99E82A75642AC823 > /tmp/sbt-key.asc &&
      apt-key add /tmp/sbt-key.asc &&
      apt-get update &&
      apt-get install -y sbt &&
      /bin/bash
      "
    ports: 
      - "8080:8080"
    networks:
      - spark-network

  spark-worker:
    image: spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]
    networks:
      - spark-network
      
networks:
  spark-network:
    driver: bridge